### PR TITLE
Flexbench desktop app (MVP)

### PR DESCRIPTION
**Pull request by Kanha-13**
PR for the first MVP release
**This pr include following issues and sub-issues:**

1. Create MVP standalone app
2. Create a GUI using electron
3. Basic requirements and UX for flexbench desktop app
4. Basic layout: Top bar menu, left sidebar, main right panel, small bottom bar
5. Top bar menu: Import | Export| create | Projects 
6. Sidebar component: create/configure collections and requests
7. Main panel: set request data (support port, method, params)

Build Check:

- [x] Able to reproduce the project on local.
- [x] Able to create new project / scenario / request
- [x] Simple / multi request working correctly
- [x] Data persist
- [x] Able to import / export projects

### CODE REVIEW

**Comment by iskitsas** [comment]
@Kanha-13 after building/installing it on a mac and playing with a simple request I get:

image

``` 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/iskitsas/Library/Preferences/flexbench_electron/Temp/configs.json'
at Object.openSync (node:fs:585:3)
at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
at Object.readFileSync (node:fs:453:35)
at e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
at runTest (/Applications/flexbench_electron.app/Contents/Resources/app.asar/tests/simple-request.js:10:27)
at Object.<anonymous> (/Applications/flexbench_electron.app/Contents/Resources/app.asar/tests/simple-request.js:66:1)
at Module._compile (node:internal/modules/cjs/loader:1118:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
at Module.load (node:internal/modules/cjs/loader:988:32)
at Module._load (node:internal/modules/cjs/loader:829:12)
```

**Comment by iskitsas** [comment]
The title of the app when installed should be `Flexbench` and not `flexbench_electron`. It would be nice to have another app image instead of the default electron logo

image

**Comment by Kanha-13** [comment]
Got it, I have encountered the same issue for Linux too. Actually it was due to hard-coded , dirr path. I will update the path for mac too. Thank you for the review.

**Comment by Kanha-13** [comment]
> The title of the app when installed should be `Flexbench` and not `flexbench_electron`. It would be nice to have another app image instead of the default electron logo
> 
> image

Sure I will update these two changes.

**Comment by iskitsas** [comment]
@Kanha-13 , I still get a similar error when clicking the RUN configuration:

image

**Comment by iskitsas** [comment]
After playing around and pushing to more requests, I was able to get this error:
image

**Comment by Kanha-13** [comment]
> @Kanha-13 , I still get a similar error when clicking the RUN configuration:
> 
> image

is single request working?

**Comment by Kanha-13** [comment]
I think the second bug is because of #27  this issue

**Comment by iskitsas** [comment]
@Kanha-13 can you resolve the conflicts?

**Comment by Kanha-13** [comment]
Ok I will push the updates

**Comment by Kanha-13** [comment]
I guess its now resolved!

**Pull request merged**
