### PR TITLE
fix for missing body data in request

### PR DESCRIPTION
**Pull request by Kanha-13**
PR for #29 and #27

**Fix for #29**

- In this fix, body data is nowgetting received by the endpoint.
- And I have also updated the example of `fileupload.js` for `POST` request.

**Fix for #27**

- Using `worker.process.pid` as `port number` for `proxy server` to resolve the conflict of port number already occupied or busy error

Files modified:

1.  main.js
2. fileupload.js

**Note:** But this fix is not working when **throttling for #29 **

### CODE REVIEW

**Comment by iskitsas** [comment]
@Kanha-13 you should checkout from develop and target the develop branch for this fix

**Comment by Kanha-13** [comment]
Ok, I will change the target branch.

**Comment by Kanha-13** [comment]
This fix is for `main lib` only and develop branch has the codes of `desktop-app` also!
So should I target `develop` ?

**Comment by iskitsas** [comment]
@Kanha-13 it is ok to target this fix towards `develop` branch. The next release we will do will also include your MVP ;)

**Comment by Kanha-13** [comment]
@iskitsas I have changed the target branch

**Comment by Kanha-13** [comment]
I have also pushed the fix for #27 in this pr.

**Pull request merged**
