### PR TITLE
Anonymization in/out | PR #76 | proposing changes

### PR DESCRIPTION
**Pull request by iskitsas**
Proposing changes for PR #76, commit: 4fa42b457e82022251602fb5051be6d3058f5521

@AJun01 , see the proposed changes. In lib/main.js I wanted to keep the same signature for cb mehtod, eg:
```
 if (cb) {
   if(anonymizer.isAnonymizationEnabled) {
     cb(anonymizer.anonymizeResponse(response));
   }else {
     cb(response)
   }
}
``` 

When anonymizer is enabled, I am using a mock response to replace the original, including an anonymized body, which the simple-request-anonymized.js test can handle with:
```
response.on('data', function (chunk) {
  console.log(chunk.length);
  console.log(chunk.toString());
});
```

This way the developer can handle the response object the same way as the normal/existing flow

### CODE REVIEW

**Comment by AJun01** [comment]
> Proposing changes for PR #76, commit: [4fa42b4](https://github.com/flexivian/flexbench/commit/4fa42b457e82022251602fb5051be6d3058f5521)
> 
> @AJun01 , see the proposed changes. In lib/main.js I wanted to keep the same signature for cb mehtod, eg:
> 
> ```
>  if (cb) {
>    if(anonymizer.isAnonymizationEnabled) {
>      cb(anonymizer.anonymizeResponse(response));
>    }else {
>      cb(response)
>    }
> }
> ```
> 
> When anonymizer is enabled, I am using a mock response to replace the original, including an anonymized body, which the simple-request-anonymized.js test can handle with:
> 
> ```
> response.on('data', function (chunk) {
>   console.log(chunk.length);
>   console.log(chunk.toString());
> });
> ```
> 
> This way the developer can handle the response object the same way as the normal/existing flow

for your proposed code: 
```
 cb(anonymizer.anonymizeResponse(response));
```

because anonymizeResponse doesn’t immediately return the anonymized data; the response object is undefined so that response.on() generated error(Cannot read properties of undefined (reading 'statusCode')) on my side. therefore, I suggest that change it into anonymizer.anonymizeResponse(response, function (anonymizedResponse) {
        cb(anonymizedResponse);
    }); so, the callback should only be invoked after the response has been fully processed.

**Comment by iskitsas** [comment]
> > Proposing changes for PR #76, commit: [4fa42b4](https://github.com/flexivian/flexbench/commit/4fa42b457e82022251602fb5051be6d3058f5521)
> > @AJun01 , see the proposed changes. In lib/main.js I wanted to keep the same signature for cb mehtod, eg:
> > ```
> >  if (cb) {
> >    if(anonymizer.isAnonymizationEnabled) {
> >      cb(anonymizer.anonymizeResponse(response));
> >    }else {
> >      cb(response)
> >    }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When anonymizer is enabled, I am using a mock response to replace the original, including an anonymized body, which the simple-request-anonymized.js test can handle with:
> > ```
> > response.on('data', function (chunk) {
> >   console.log(chunk.length);
> >   console.log(chunk.toString());
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way the developer can handle the response object the same way as the normal/existing flow
> 
> for your proposed code:
> 
> ```
>  cb(anonymizer.anonymizeResponse(response));
> ```
> 
> because anonymizeResponse doesn’t immediately return the anonymized data; the response object is undefined so that response.on() generated error(Cannot read properties of undefined (reading 'statusCode')) on my side. therefore, I suggest that change it into
> 
> ```
> anonymizer.anonymizeResponse(response, function (anonymizedResponse) {
>         cb(anonymizedResponse);
>     });
> ```
> 
> so, the callback should only be invoked after the response has been fully processed.

Did you run a specific test where you got this error?

**Comment by iskitsas** [comment]
> > > Proposing changes for PR #76, commit: [4fa42b4](https://github.com/flexivian/flexbench/commit/4fa42b457e82022251602fb5051be6d3058f5521)
> > > @AJun01 , see the proposed changes. In lib/main.js I wanted to keep the same signature for cb mehtod, eg:
> > > ```
> > >  if (cb) {
> > >    if(anonymizer.isAnonymizationEnabled) {
> > >      cb(anonymizer.anonymizeResponse(response));
> > >    }else {
> > >      cb(response)
> > >    }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > When anonymizer is enabled, I am using a mock response to replace the original, including an anonymized body, which the simple-request-anonymized.js test can handle with:
> > > ```
> > > response.on('data', function (chunk) {
> > >   console.log(chunk.length);
> > >   console.log(chunk.toString());
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This way the developer can handle the response object the same way as the normal/existing flow
> > 
> > 
> > for your proposed code:
> > ```
> >  cb(anonymizer.anonymizeResponse(response));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because anonymizeResponse doesn’t immediately return the anonymized data; the response object is undefined so that response.on() generated error(Cannot read properties of undefined (reading 'statusCode')) on my side. therefore, I suggest that change it into
> > ```
> > anonymizer.anonymizeResponse(response, function (anonymizedResponse) {
> >         cb(anonymizedResponse);
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so, the callback should only be invoked after the response has been fully processed.
> 
> Did you run a specific test where you got this error?

I am running the `example/simple-request-anonymized.js` from terminal or IDE (with debugger attached) and I do not see any error. The returned mocked response has initially set the status code from original response, and the data of the body will be streamed and captured through the `response.on('data')..` 

image

image

image

**Comment by AJun01** [comment]
Yea, worked, sorry I was missing the const { PassThrough } = require('stream');

**Comment by AJun01** [comment]
Thank you for your proposed changes! I am pushing the changes to my old PR, I will start from there.

**Pull request closed without merging**
